### ISSUE TITLE
Class constructor Comment cannot be invoked without 'new'

### ISSUE THREAD

**Issue by kedarguy** [NoamELB/shouldComponentUpdate-Children#1]
When adding the package and using the HOC on one of the components I get the following Error:

`Uncaught TypeError: Class constructor Comment cannot be invoked without 'new'
    at new ShallowEqualEnhancer (main.bundle.js:77123)
    at constructClassInstance (main.bundle.js:33250)
    at updateClassComponent (main.bundle.js:33705)
    at beginWork (main.bundle.js:34095)
    at performUnitOfWork (main.bundle.js:36063)
    at workLoop (main.bundle.js:36172)
    at HTMLUnknownElement.callCallback (main.bundle.js:24789)
    at Object.invokeGuardedCallbackDev (main.bundle.js:24828)
    at invokeGuardedCallback (main.bundle.js:24685)
    at performWork (main.bundle.js:36290) main.bundle.js:31795` 

`The above error occurred in the <ShallowEqualEnhancedComment> component:
    in ShallowEqualEnhancedComment (created by CommentList)
    in div (created by wrapperStyle)
    in wrapperStyle (created by wrapperStyle)
...`

stack includes next.js 4 and react 16

**Comment by NoamELB** [comment]
Hi, can please you provide a snippet of your code or maybe even create a codepen with this reproduced?
Thanks!

**Comment by kedarguy** [comment]
We have a pretty custom stack :weary: 
Tried to reproduce with a fresh next.js app and it worked, so I'm having a hard time finding where the conflict is.
I will try to isolate the issue and update

**Comment by NoamELB** [comment]
Thank! Appreciate it! 😄
I'm adding another usage as a plain function (see issue #2), this might help for you as well.

**Comment by hinok** [comment]
@NoamELB I encountered this problem in my project after upgrading to babel 7.

I use `@babel/preset-env` with `targets: { node: 'current' }` for server bundle which basically doesn't transpile classes because they are already supported in modern node.

Code from `node_modules` is not transpiled at all by babel and the published package contains code transpiled by babel (without native classes).

This error appears because [transpiled classes cannot extend native classes](https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne).

Could you publish a version with native classes?

**Comment by NoamELB** [comment]
@hinok Are you using the common js file for Node? 
(https://github.com/NoamELB/shouldComponentUpdate-Children/blob/master/index.cjs.js)

**Comment by hinok** [comment]
@NoamELB `cjs.js` and `es.js`, they don't contain native classes so it doesn't matter what is picked up by webpack/node.

After inspecting transpiled code, I just see `require()` call so node is probably loading `cjs.js`.

**Comment by lpoulter** [comment]
I fixed this by importing `index.js` like so.
`import { useShallowEqual } from "shouldcomponentupdate-children/index.js";`
A better fix might be to update the transpired versions of the lib.
